// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_beta1_se
List compute_beta1_se(NumericMatrix Phi, NumericVector coef, NumericMatrix cov_matrix, IntegerVector sel_idx);
RcppExport SEXP _WasserSpectrum_compute_beta1_se(SEXP PhiSEXP, SEXP coefSEXP, SEXP cov_matrixSEXP, SEXP sel_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Phi(PhiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type cov_matrix(cov_matrixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sel_idx(sel_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_beta1_se(Phi, coef, cov_matrix, sel_idx));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WasserSpectrum_compute_beta1_se", (DL_FUNC) &_WasserSpectrum_compute_beta1_se, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_WasserSpectrum(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
