# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_beta1_se <- function(Phi, coef, cov_matrix, sel_idx) {
    .Call(`_WasserSpectrum_compute_beta1_se`, Phi, coef, cov_matrix, sel_idx)
}

compute_l1_dist_matrix <- function(M) {
    .Call(`_WasserSpectrum_compute_l1_dist_matrix`, M)
}

